AADWebApp/Areas/Technician/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AADWebApp.Areas.Technician.Pages
{
    [Authorize(Roles = "Technician, Admin")]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AADWebApp/Areas/Technician/Pages/ProcessPrescriptions.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AADWebApp.Interfaces;
using AADWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static AADWebApp.Services.PrescriptionCollectionService;

namespace AADWebApp.Areas.Technician.Pages
{
    public class ProcessPrescriptionsModel : PageModel
    {
        private readonly IPrescriptionService _prescriptionService;
        private readonly IMedicationService _medicationService;
        private readonly IPrescriptionCollectionService _prescriptionCollectionService;

        public List<Prescription> Prescriptions { get; private set; } = new List<Prescription>();
        public List<Medication> Medications { get; private set; } = new List<Medication>();
        public List<List<PrescriptionCollection>> PrescriptionCollections { get; private set; } = new List<List<PrescriptionCollection>>();

        [BindProperty]
        public int PrescriptionCollectionId { get; set; }

        [BindProperty]
        public string SearchTerm { get; set; }

        public ProcessPrescriptionsModel(IPrescriptionService prescriptionService, IMedicationService medicationService, IPrescriptionCollectionService prescriptionCollectionService)
        {
            _prescriptionService = prescriptionService;
            _medicationService = medicationService;
            _prescriptionCollectionService = prescriptionCollectionService;
        }

        public void OnGet()
        {
            InitPage();
        }

        public void OnPostPrepared()
        {
            InitPage();

            var result = _prescriptionCollectionService.SetPrescriptionCollectionStatus((short) PrescriptionCollectionId, CollectionStatus.BeingPrepared);

            InitPage();

            if (result == 1)
            {
                TempData["EnterPrescriptionStatusSuccess"] = $"Status for prescription collection {PrescriptionCollectionId} was set to Being Prepared.";
            }
            else
            {
                TempData["EnterPrescriptionStatusFailure"] = $"Prescription collection service returned error value.";
            }
        }

        public void OnPostReady()
        {
            InitPage();

            var result = _prescriptionCollectionService.SetPrescriptionCollectionStatus((short) PrescriptionCollectionId, CollectionStatus.CollectionReady);

            InitPage();

            if (result == 1)
            {
                TempData["EnterPrescriptionStatusSuccess"] = $"Status for prescription collection {PrescriptionCollectionId} was set to Collection Ready.";
            }
            else
            {
                TempData["EnterPrescriptionStatusFailure"] = $"Prescription Collection service returned error value.";
            }
        }

        public void OnPostCollected()
        {
            InitPage();

            var result = _prescriptionCollectionService.SetPrescriptionCollectionCollected((short) PrescriptionCollectionId);

            InitPage();

            if (result == 1)
            {
                TempData["EnterPrescriptionStatusSuccess"] = $"Status for prescription collection {PrescriptionCollectionId} was set to Collected.";
            }
            else
            {
                TempData["EnterPrescriptionStatusFailure"] = $"Prescription collection service returned error value.";
            }
        }

        public async Task OnPostSearchAsync()
        {
            var medicationIds = _medicationService.GetMedications().Where(item => item.MedicationName.Contains(SearchTerm)).OrderBy(item => item.MedicationName).Select(item => item.Id);

            Prescriptions = _prescriptionService.GetPrescriptions().Where(item => medicationIds.Contains(item.MedicationId)).ToList();

            foreach (var item in Prescriptions)
            {
                Medications.Add(_medicationService.GetMedications(item.MedicationId).ElementAt(0));

                PrescriptionCollections.Add(_prescriptionCollectionService.GetPrescriptionCollectionsByPrescriptionId(item.Id).ToList());
            }
        }

        private void InitPage()
        {
            Prescriptions = new List<Prescription>();
            Medications = new List<Medication>();
            PrescriptionCollections = new List<List<PrescriptionCollection>>();

            Prescriptions = _prescriptionService.GetPrescriptions().ToList();

            foreach (var item in Prescriptions)
            {
                Medications.Add(_medicationService.GetMedications(item.MedicationId).ElementAt(0));

                PrescriptionCollections.Add(_prescriptionCollectionService.GetPrescriptionCollectionsByPrescriptionId(item.Id).ToList());
            }
        }
    }
}

AADWebApp/Areas/Technician/Pages/Index.cshtml
@page
@model AADWebApp.Areas.Technician.Pages.IndexModel
@{
    ViewData["Title"] = "Technician Home";
    Layout = "~/Areas/Technician/Pages/_TechnicianLayout.cshtml";
}

<h1 class="mt-5 mb-5">Technician Home</h1>
    <div class="card-deck mt-5 mb-5">
            <div class="card ml-5">
                <img class="card-img-top" src="~/lib/Images/MedicineCabinet.png">
                <div class="card-body">
                    <a class="text-dark" asp-area="Technician" asp-page="/ProcessPrescriptions">
                        <h5 class="card-title"> <b>Process Prescriptions</b></h5>
                    </a>
                    <p class="card-text">Process Prescriptions and get them ready for preparation.</p>
                </div>
            </div>
            <div class="card ml-5">
                <img class="card-img-top" src="~/lib/Images/Pills.png">
                <div class="card-body">
                    <a class="text-dark" asp-area="Technician" asp-page="/ProcessPrescriptions">
                        <h5 class="card-title"><b> Check Prescription Status</b></h5>
                    </a>
                        <p class="card-text">Be alerted whether a prescription is ready or collected.</p>
                        </div>
            </div>
    </div>

AADWebApp/Areas/Technician/Pages/ProcessPrescriptions.cshtml
@page
@using AADWebApp.Services
@model AADWebApp.Areas.Technician.Pages.ProcessPrescriptionsModel
@{
    ViewData["Title"] = "Process Prescriptions";
    Layout = "~/Areas/Technician/Pages/_TechnicianLayout.cshtml";
}

<h1 class="mb-5">Process Prescription Collections</h1>

<h3 class="mb-5">Search</h3>

<div id=" Search" class="form-group form-inline mb-5">
    <form method="post" class="form-inline">
        <div class="form-group">
            <label for="medication-name" class="mr-5">Medication Name</label>
            <input type="text" class="form-control mr-5" id="medication-name" name="SearchTerm" placeholder="Medication Name">
        </div>
        <button type="submit" asp-page-handler="Search" class="btn btn-primary">Search</button>
    </form>
    <form method="get">
        <button type="submit" asp-page-handler="OnGet" class="btn btn-primary ml-5">Clear</button>
    </form>
</div>

<h2 class="mb-5">Collections Pending</h2>

@if (TempData["EnterPrescriptionStatusSuccess"] != null)
{
    <p class="mb-2 p-2 bg-success text-white rounded">@TempData["EnterPrescriptionStatusSuccess"]</p>
}
else if (TempData["EnterPrescriptionStatusFailure"] != null)
{
    <p class="mb-2 p-2 bg-danger text-white rounded">@TempData["EnterPrescriptionStatusFailure"]</p>
}

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Prescription ID</th>
            <th scope="col">Medication Name</th>
            <th scope="col">Dosage</th>
            <th scope="col">Prescription Start</th>
            <th scope="col">Prescription End</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Prescriptions.Count; i++)
        {
            @for (var x = 0; x < Model.PrescriptionCollections[i].Count; x++)
            {
                <form method="post">
                    <tr>
                        <input type="hidden" value="@Model.PrescriptionCollections[i].ElementAt(x).Id" name="PrescriptionCollectionId" />
                        @if (Model.PrescriptionCollections[i].ElementAt(x).CollectionStatus == PrescriptionCollectionService.CollectionStatus.Pending)
                        {
                            <td>@Model.Prescriptions[i].Id</td>
                            <td>@Model.Medications[i].MedicationName</td>
                            <td>@Model.Prescriptions[i].Dosage</td>
                            <td>@Model.Prescriptions[i].DateStart</td>
                            <td>@Model.Prescriptions[i].DateEnd</td>
                            <td>
                                <input type="submit" class="btn btn-success float-right" value="Being Prepared" asp-page-handler="Prepared" />
                            </td>
                        }
                    </tr>
                </form>
            }
        }
    </tbody>
</table>

<br />
<h2 class="mb-5">Collections Being Prepared</h2>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Prescription ID</th>
            <th scope="col">Medication Name</th>
            <th scope="col">Dosage</th>
            <th scope="col">Prescription Start</th>
            <th scope="col">Prescription End</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Prescriptions.Count; i++)
        {
            @for (var x = 0; x < Model.PrescriptionCollections[i].Count; x++)
            {
                <form method="post">
                    <tr>
                        <input type="hidden" value="@Model.PrescriptionCollections[i].ElementAt(x).Id" name="PrescriptionCollectionId" />
                        @if (Model.PrescriptionCollections[i].ElementAt(x).CollectionStatus == PrescriptionCollectionService.CollectionStatus.BeingPrepared)
                        {
                            <td>@Model.Prescriptions[i].Id</td>
                            <td>@Model.Medications[i].MedicationName</td>
                            <td>@Model.Prescriptions[i].Dosage</td>
                            <td>@Model.Prescriptions[i].DateStart</td>
                            <td>@Model.Prescriptions[i].DateEnd</td>
                            <td>
                                <input type="submit" class="btn btn-success float-right" value="Collection Ready" asp-page-handler="Ready" />
                            </td>
                        }
                    </tr>
                </form>
            }
        }
    </tbody>
</table>

<br />
<h2 class="mb-5">Collections Ready</h2>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Prescription ID</th>
            <th scope="col">Medication Name</th>
            <th scope="col">Dosage</th>
            <th scope="col">Prescription Start</th>
            <th scope="col">Prescription End</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Prescriptions.Count; i++)
        {
            @for (var x = 0; x < Model.PrescriptionCollections[i].Count; x++)
            {
                <form method="post">
                    <tr>
                        <input type="hidden" value="@Model.PrescriptionCollections[i].ElementAt(x).Id" name="PrescriptionCollectionId" />
                        @if (Model.PrescriptionCollections[i].ElementAt(x).CollectionStatus == PrescriptionCollectionService.CollectionStatus.CollectionReady)
                        {
                            <td>@Model.Prescriptions[i].Id</td>
                            <td>@Model.Medications[i].MedicationName</td>
                            <td>@Model.Prescriptions[i].Dosage</td>
                            <td>@Model.Prescriptions[i].DateStart</td>
                            <td>@Model.Prescriptions[i].DateEnd</td>
                            <td>
                                <input type="submit" class="btn btn-success float-right" value="Collected" asp-page-handler="Collected" />
                            </td>
                        }
                    </tr>
                </form>
            }
        }
    </tbody>
</table>

<br />
<h2 class="mb-5">Prescriptions Collected</h2>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Prescription ID</th>
            <th scope="col">Medication Name</th>
            <th scope="col">Dosage</th>
            <th scope="col">Prescription Start</th>
            <th scope="col">Prescription End</th>
            <th scope="col">Collected At</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Prescriptions.Count; i++)
        {
            @for (var x = 0; x < Model.PrescriptionCollections[i].Count; x++)
            {
                <form method="post">
                    <tr>
                        <input type="hidden" value="@Model.PrescriptionCollections[i].ElementAt(x).Id" name="PrescriptionCollectionId" />
                        @if (Model.PrescriptionCollections[i].ElementAt(x).CollectionStatus == PrescriptionCollectionService.CollectionStatus.Collected)
                        {
                            <td>@Model.Prescriptions[i].Id</td>
                            <td>@Model.Medications[i].MedicationName</td>
                            <td>@Model.Prescriptions[i].Dosage</td>
                            <td>@Model.Prescriptions[i].DateStart</td>
                            <td>@Model.Prescriptions[i].DateEnd</td>

                            <td>@Model.PrescriptionCollections[i].ElementAt(x).CollectionTime</td>
                        }
                    </tr>
                </form>
            }
        }
    </tbody>
</table>

AADWebApp/Areas/Technician/Pages/_TechnicianLayout.cshtml
@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        @RenderBody()
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", false)

    <script>
    $(function () {
        var current = location.pathname;
        $(' .nav-tabs li a').each(function () {
            var $this = $(this);
            if (current.indexOf($this.attr('href')) !== -1) {
                $this.addClass('active');
            }
        })
    })
    </script>
}

AADWebApp/Areas/Technician/Pages/_TechnicianPartial.cshtml
@inject SignInManager<ApplicationUser> SignInManager

@if (SignInManager.IsSignedIn(User) && User.IsInRole("Technician"))
{
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Technician" asp-page="/Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Technician" asp-page="/ProcessPrescriptions">Process Prescription Collections</a>
            </li>
        </ul>
    </div>
}