AADWebApp/Areas/Admin/Pages/CreateRole.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using AADWebApp.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AADWebApp.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin")]
    public class CreateRoleModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public CreateRoleModel(
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            public string RoleName { get; set; }
        }

        public void OnGet()
        {
            if (!User.Identity.IsAuthenticated) Response.Redirect("/");
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                var newRole = new IdentityRole
                {
                    Name = Input.RoleName
                };

                var result = await _roleManager.CreateAsync(newRole);

                if (result.Succeeded) return Redirect("/Admin/ListRoles");

                foreach (var error in result.Errors) ModelState.AddModelError("", error.Description);
            }

            return Page();
        }
    }
}

AADWebApp/Areas/Admin/Pages/EditRole.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AADWebApp.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AADWebApp.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin")]
    public class EditRoleModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        [BindProperty]
        public RoleModel roleModel { get; set; }

        public class RoleModel
        {
            public string Id { get; set; }
            public string RoleName { get; set; }

            public List<string> Users { get; set; } = new List<string>();
        }

        public EditRoleModel(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            roleModel = new RoleModel();
        }

        public async Task OnGet()
        {
            var role = await _roleManager.FindByIdAsync(Request.Query["id"]);

            if (role == null)
            {
                ModelState.AddModelError("", "Role not found");
                Response.Redirect("/Admin/ListRoles");
            }
            else
            {
                roleModel.Id = role.Id;
                roleModel.RoleName = role.Name;

                //userManager can only have one connection going at a time, so the info we need is cast to a seperate list object, see https://stackoverflow.com/a/60730238
                foreach (var user in _userManager.Users.ToList())
                    if (await _userManager.IsInRoleAsync(user, role.Name))
                        roleModel.Users.Add(user.UserName);
            }
        }

        public async Task OnPostAsync()
        {
            var role = await _roleManager.FindByIdAsync(Request.Query["id"]);

            if (role == null)
            {
                ModelState.AddModelError("", "Role not found");
            }
            else
            {
                role.Name = roleModel.RoleName;
                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                    Response.Redirect("/Admin/ListRoles");
                else
                    foreach (var error in result.Errors)
                        ModelState.AddModelError("", error.Description);
            }

            await OnGet();
        }
    }
}

AADWebApp/Areas/Admin/Pages/EditRoleUsers.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AADWebApp.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AADWebApp.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin")]
    public class EditRoleUsersModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        [BindProperty]
        public List<UserRoleModel> UserRoleModels { get; set; } = new List<UserRoleModel>();

        public class UserRoleModel
        {
            public string UserId { get; set; }
            public string UserName { get; set; }
            public bool IsSelected { get; set; }
        }

        public string RoleName { get; private set; }

        public EditRoleUsersModel(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task OnGet()
        {
            var role = await _roleManager.FindByIdAsync(Request.Query["id"]);

            if (role == null)
            {
                ModelState.AddModelError("EditRoleError", "Role not found");
                return;
            }

            RoleName = role.Name;

            //Same fix as EditRole, see https://stackoverflow.com/a/60730238
            foreach (var user in _userManager.Users.ToList())
            {
                UserRoleModels.Add(new UserRoleModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = await _userManager.IsInRoleAsync(user, role.Name)
                });
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var roleId = Request.Query["id"];
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ModelState.AddModelError("EditRoleError", "Role not found");
                return Page();
            }

            foreach (var userRoleModel in UserRoleModels)
            {
                var user = await _userManager.FindByIdAsync(userRoleModel.UserId);

                if (user == null)
                {
                    ModelState.AddModelError("EditRoleError", "No user with ID '" + userRoleModel.UserId + "' found");
                    continue;
                }

                var result = userRoleModel.IsSelected switch
                {
                    true when !await _userManager.IsInRoleAsync(user, role.Name) => await _userManager.AddToRoleAsync(user, role.Name),
                    false when await _userManager.IsInRoleAsync(user, role.Name) => await _userManager.RemoveFromRoleAsync(user, role.Name),
                    _ => null
                };

                if (result?.Succeeded == false) break;
            }

            return ModelState.ErrorCount == 0 ? (IActionResult) Redirect("/Admin/EditRole?id=" + roleId) : Page();
        }
    }
}

AADWebApp/Areas/Admin/Pages/ListRoles.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AADWebApp.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin")]
    public class ListRolesModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        [BindProperty]
        public string RoleId { get; set; }

        public ListRolesModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public void OnGet()
        {
            if (!User.Identity.IsAuthenticated) Response.Redirect("/");
        }

        public async Task<IActionResult> OnPost()
        {
            Console.WriteLine("Role to delete: " + RoleId);

            var role = await _roleManager.FindByIdAsync(RoleId);

            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);

                if (result.Succeeded)
                    Response.Redirect("/Admin/ListRoles");
                else
                    foreach (var error in result.Errors)
                        ModelState.AddModelError("", error.Description);
            }
            else
            {
                ModelState.AddModelError("", "Role not found");
            }

            return Page();
        }
    }
}

AADWebApp/Areas/Admin/Pages/ListUsers.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using AADWebApp.Areas.Identity.Data;
using AADWebApp.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.WebUtilities;

namespace AADWebApp.Areas.Admin.Pages
{
    [Authorize(Roles = "Admin")]
    public class ListUsersModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ISendEmailService _sendEmailService;

        [BindProperty]
        public InputModel Input { get; set; }

        [BindProperty]
        public string UserId { get; set; }

        public ListUsersModel(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, ISendEmailService sendEmailService)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _sendEmailService = sendEmailService;

            Roles = new SelectList(_roleManager.Roles.ToList());
        }

        public SelectList Roles { get; set; }

        public class InputModel
        {
            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Select a role for the new user")]
            public string Role { get; set; }
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostDeleteUserAsync()
        {
            Console.WriteLine("UserID to delete: " + UserId);

            var user = await _userManager.FindByIdAsync(UserId);

            if (user != null)
            {
                var deleteResult = await _userManager.DeleteAsync(user);

                if (deleteResult.Succeeded)
                    Response.Redirect("/Admin/ListUsers");
                else
                    foreach (var error in deleteResult.Errors)
                        ModelState.AddModelError("", error.Description);
            }
            else
            {
                ModelState.AddModelError("", "User not found");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostIssuePasswordResetAsync()
        {
            Console.WriteLine("UserID to issue password reset for: " + UserId);

            var user = await _userManager.FindByIdAsync(UserId);

            if (user != null)
            {
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    null,
                    new
                    {
                        area = "Identity",
                        code
                    },
                    Request.Scheme);

                _sendEmailService.SendEmail(
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.",
                    "Reset Password",
                    user.Email
                );

                TempData["PasswordResetSuccess"] = $"Password reset issued for {user.Email}.";
            }
            else
            {
                ModelState.AddModelError("", "User not found");
            }

            return Page();
        }
    }
}

AADWebApp/Areas/Admin/Pages/CreateRole.cshtml
@page
@model AADWebApp.Areas.Admin.Pages.CreateRoleModel

@{
    ViewData["Title"] = "Create Role";
    Layout = "~/Areas/Admin/Pages/_AdminLayout.cshtml";
}

<h1>Create Role</h1>
<div class="col-md-10 offset-md-1">
    <section>
        <form asp-route-returnUrl="@Model.ReturnUrl" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.RoleName"></label>
                <input asp-for="Input.RoleName" class="form-control" />
                <span asp-validation-for="Input.RoleName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Create Role</button>
        </form>
    </section>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

AADWebApp/Areas/Admin/Pages/EditRole.cshtml
@page
@model AADWebApp.Areas.Admin.Pages.EditRoleModel
@{
    ViewData["Title"] = "Edit Role";
    Layout = "~/Areas/Admin/Pages/_AdminLayout.cshtml";
}

<h1>Edit Role</h1>
<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="roleModel.Id" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="roleModel.Id" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="roleModel.RoleName" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <input asp-for="roleModel.RoleName" class="form-control">
            <span asp-validation-for="roleModel.RoleName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-md-6">
            <a class="btn btn-danger w-100" asp-area="Admin" asp-page="/ListRoles">Cancel</a>
        </div>
        <div class="col-md-6">
            <button type="submit" class="btn btn-success w-100">Update</button>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Users in this role:</h3>
        </div>
        <div class="card-body">
            @if (Model.roleModel.Users.Any())
            {
                <table class="table">
                    @foreach (var user in Model.roleModel.Users)
                    {
                        <tr>
                            <th>User Name</th>
                            <td>@user</td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <h5 class="card-title">No Users</h5>
            }
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" style="width:auto" asp-area="Admin" asp-page="/EditRoleUsers" asp-route-id="@Model.roleModel.Id">Add or Remove Users</a>
        </div>
    </div>
</form>

AADWebApp/Areas/Admin/Pages/EditRoleUsers.cshtml
@page
@using Microsoft.AspNetCore.Mvc.ModelBinding
@model AADWebApp.Areas.Admin.Pages.EditRoleUsersModel

@{
    ViewData["Title"] = "Edit Role Users";
    var roleId = Request.Query["id"];
    Layout = "~/Areas/Admin/Pages/_AdminLayout.cshtml";
}

@{
    if (Model.ModelState.TryGetValue("EditRoleError", out var roleErrors))
    {
        <p class="text-danger font-weight-bold">Errors:</p>
        <ul>
            @foreach (var error in roleErrors.Errors)
            {
                <li class="text-danger">@error.ErrorMessage</li>
            }
        </ul>

        <p class="text-danger">Please try again.</p>
        <a class="btn btn-danger" asp-area="Admin" asp-page="/EditRole" asp-route-id="@roleId">Return</a>

        return;
    }
    <h1>Edit '@Model.RoleName' Role Users</h1>
    <form method="post">
        <div class="card">
            <div class="card-header">
                <h2>Add or remove users from role:</h2>
            </div>
            <div class="card-body">
                @for (var i = 0; i < Model.UserRoleModels.Count; i++)
                {
                    <div class="form-check m-1">
                        @if (Model.UserRoleModels[i].IsSelected)
                        {
                            <input asp-for="@Model.UserRoleModels[i].IsSelected" checked class="form-check-input" />
                        }
                        else
                        {
                            <input asp-for="@Model.UserRoleModels[i].IsSelected" class="form-check-input" />
                        }
                        <input asp-for="@Model.UserRoleModels[i].UserId" value="@Model.UserRoleModels[i].UserId" type="hidden">
                        <input asp-for="@Model.UserRoleModels[i].UserName" value="@Model.UserRoleModels[i].UserName" type="hidden">
                        <label class="form-check-label">@Model.UserRoleModels[i].UserName</label>
                    </div>
                }
            </div>
            <div class="card-footer">
                <a class="btn btn-danger" asp-area="Admin" asp-page="/EditRole" asp-route-id="@roleId">Cancel</a>
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </form>
}

AADWebApp/Areas/Admin/Pages/ListRoles.cshtml
@page
@model AADWebApp.Areas.Admin.Pages.ListRolesModel
@inject RoleManager<IdentityRole> RoleManager;

@{
    ViewData["Title"] = "List Roles";
    Layout = "~/Areas/Admin/Pages/_AdminLayout.cshtml";
}

<h1>List Roles</h1>
@if (RoleManager.Roles.Any())
{
    <a class="btn btn-primary mb-3" asp-area="Admin" asp-page="/CreateRole">Create role</a>

    <div class="row">
        @foreach (var role in RoleManager.Roles)
        {
            <div class="col-md-6 mb-3 d-flex align-items-stretch">
                <div class="card w-100">
                    <div class="card-header">Role ID : @role.Id</div>
                    <div class="card-body">
                        <h5 class="card-title">Role Name : @role.Name</h5>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-warning" asp-area="Admin" asp-page="/EditRole" asp-route-id="@role.Id">Edit</a>
                        <form method="post" class="d-inline">
                            <input asp-for="RoleId" value="@role.Id" type="hidden">
                            <button type="submit" asp class="btn btn-danger" onclick="return confirm('Are you sure you want to delete role: @role.Name?')">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="card">
        <div class="card-header">No roles created yet</div>
        <div class="card-body">
            <h5 class="card-title">Use button below to create a role</h5>
            <a class="btn btn-primary" asp-area="Admin" asp-page="/CreateRole">Create role</a>
        </div>
    </div>
}

AADWebApp/Areas/Admin/Pages/ListUsers.cshtml
@page
@model AADWebApp.Areas.Admin.Pages.ListUsersModel
@inject UserManager<ApplicationUser> UserManager;

@{
    ViewData["Title"] = "List Users";
    Layout = "~/Areas/Admin/Pages/_AdminLayout.cshtml";
}

<h1>List Users</h1>
@if (UserManager.Users.Any())
{
    <button type='button' class='btn btn-primary mb-2' data-toggle='modal' data-target='#user-type-modal'>Create user</button>

    @if (TempData["PasswordResetSuccess"] != null)
    {
        <p class="mb-2 p-2 bg-success text-white rounded">@TempData["PasswordResetSuccess"]</p>
    }

    <div class="row">
        @foreach (var user in UserManager.Users)
        {
            <div class="col-md-6 mb-3 d-flex align-items-stretch">
                <div class="card w-100">
                    <div class="card-header">User ID : @user.Id</div>
                    <div class="card-body">
                        <table class="table table-sm">
                            <tr>
                                <th>User Name</th>
                                <td>@user.FirstName @user.LastName</td>
                            </tr>
                            <tr>
                                <th>Email Address</th>
                                <td>@user.Email</td>
                            </tr>
                            <tr>
                                <th>Phone Number</th>
                                <td>@user.PhoneNumber</td>
                            </tr>
                            <tr>
                                <th>NHS Number</th>
                                <td>@user.NHSNumber</td>
                            </tr>
                            <tr>
                                <th>City</th>
                                <td>@user.City</td>
                            </tr>
                            <tr>
                                <th>General Practioner</th>
                                <td>@user.GeneralPractioner</td>
                            </tr>
                            <tr>
                                <th>First Name</th>
                                <td>@user.FirstName</td>
                            </tr>
                            <tr>
                                <th>Last Name</th>
                                <td>@user.LastName</td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer">
                        <form method="post">
                            <input asp-for="UserId" value="@user.Id" type="hidden">
                            <div class="d-flex">
                                <div class="w-100 d-flex mr-2">
                                    <input type="submit" asp-page-handler="IssuePasswordReset" value="Issue password reset" asp class="btn btn-warning" onclick="return confirm('Are you sure you want to issue a password reset for user: @user.UserName?')" />
                                </div>
                                <input type="submit" asp-page-handler="DeleteUser" value="Delete" asp class="btn btn-danger" onclick="return confirm('Are you sure you want to delete user: @user.UserName?')" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="card">
        <div class="card-header">No users created yet</div>
        <div class="card-body">
            <h5 class="card-title">Use button below to create a user</h5>
            <a class="btn btn-primary" style="width:auto" asp-area="Identity" asp-page="/Account/Register">Create user</a>
        </div>
    </div>
}

<!-- User type selection modal -->
<div class="modal fade" id="user-type-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create a user</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>

            <form method="GET" asp-area="Identity" asp-page="/Account/Register">
                <div class="modal-body">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Input.Role" class="control-label"></label>
                        <select asp-for="Input.Role" class="form-control" asp-items="@Model.Roles" required>
                            <option value="">Select an option</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" value="Cancel" class="btn btn-danger" data-dismiss="modal" />
                    <input type="submit" value="Create user" class="btn btn-success" id="js-action-btn" />
                </div>
            </form>
        </div>
    </div>
</div>

AADWebApp/Areas/Admin/Pages/_AdminLayout.cshtml
@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        @RenderBody()
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", false)

    <script>
    $(function () {
        var current = location.pathname;
        $(' .nav-tabs li a').each(function () {
            var $this = $(this);
            if (current.indexOf($this.attr('href')) !== -1) {
                $this.addClass('active');
            }
        })
    })
    </script>
}

AADWebApp/Areas/Admin/Pages/_AdminPartial.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-dark" id="register" asp-area="Admin" asp-page="/ListUsers">Manage Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" id="login" asp-area="Admin" asp-page="/ListRoles">Manage Roles</a>
            </li>

        </ul>
    </div>
}