AADWebApp/Areas/GeneralPractitioner/Pages/CancelPrescription.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AADWebApp.Areas.Identity.Data;
using AADWebApp.Interfaces;
using AADWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AADWebApp.Areas.GeneralPractitioner.Pages
{
    [Authorize(Roles = "General Practitioner, Admin")]
    public class CancelPrescriptionModel : PageModel
    {
        private readonly IPrescriptionService _prescriptionService;
        private readonly IMedicationService _medicationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public List<Prescription> Prescriptions { get; set; } = new List<Prescription>();
        public List<Medication> Medications { get; } = new List<Medication>();
        public List<ApplicationUser> Patients { get; } = new List<ApplicationUser>();

        [BindProperty]
        public int Id { get; set; }

        [BindProperty]
        public string SearchTerm { get; set; }

        public CancelPrescriptionModel(IPrescriptionService prescriptionService, IMedicationService medicationService, UserManager<ApplicationUser> userManager)
        {
            _prescriptionService = prescriptionService;
            _medicationService = medicationService;
            _userManager = userManager;
        }

        public async Task OnGetAsync()
        {
            await InitPageAsync();
        }

        public async Task OnPostAsync()
        {
            var cancelResult = await _prescriptionService.CancelPrescriptionAsync((short) Id);

            await InitPageAsync();

            if (cancelResult == 1)
            {
                TempData["PrescriptionCancelSuccess"] = $"Prescription with ID {Id} successfully cancelled.";
            }
            else
            {
                TempData["PrescriptionCancelFailure"] = $"Prescription returned error value";
            }
        }

        public async Task OnPostSearchAsync()
        {
            var patientIds = _userManager.Users.Where(item => item.FirstName.Contains(SearchTerm) || item.LastName.Contains(SearchTerm)).Select(item => item.Id);

            Prescriptions = _prescriptionService.GetPrescriptions().Where(item => patientIds.Contains(item.PatientId)).OrderBy(item => item.Id).ToList();

            foreach (var item in Prescriptions)
            {
                Medications.Add(_medicationService.GetMedications(item.MedicationId).ElementAt(0));
                Patients.Add(await _userManager.FindByIdAsync(item.PatientId));
            }
        }

        private async Task InitPageAsync()
        {
            Prescriptions = _prescriptionService.GetPrescriptions().OrderBy(item => item.PrescriptionStatus).ToList();

            foreach (var item in Prescriptions)
            {
                Medications.Add(_medicationService.GetMedications(item.MedicationId).ElementAt(0));
                Patients.Add(await _userManager.FindByIdAsync(item.PatientId));
            }
        }
    }
}

AADWebApp/Areas/GeneralPractitioner/Pages/EnterTestResults.cshtml.cs
using AADWebApp.Areas.Identity.Data;
using AADWebApp.Interfaces;
using AADWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static AADWebApp.Services.BloodTestService;
using static AADWebApp.Services.PrescriptionService;

namespace AADWebApp.Areas.GeneralPractitioner.Pages
{
    [Authorize(Roles = "General Practitioner, Admin")]
    public class EnterTestResultsModel : PageModel
    {
        private readonly IBloodTestService _bloodTestService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IPrescriptionService _prescriptionService;

        public List<BloodTest> BloodTests { get; private set; } = new List<BloodTest>();
        public List<BloodTestRequest> BloodTestRequests { get; private set; } = new List<BloodTestRequest>();
        public List<ApplicationUser> Patients { get; } = new List<ApplicationUser>();
        public List<Prescription> Prescriptions { get; set; } = new List<Prescription>();

        [BindProperty]
        public int BloodTestRequestId { get; set; }

        [BindProperty]
        public bool BloodTestResult { get; set; }

        [BindProperty]
        public DateTime BloodTestDateTime { get; set; }

        [BindProperty]
        public string SearchTerm { get; set; }

        public EnterTestResultsModel(IBloodTestService bloodTestService, UserManager<ApplicationUser> userManager, IPrescriptionService prescriptionService)
        {
            _bloodTestService = bloodTestService;
            _userManager = userManager;
            _prescriptionService = prescriptionService;
        }

        public async Task OnGetAsync()
        {
            await InitPageAsync();
        }

        public async Task OnPostAsync()
        {
            await InitPageAsync();

            var bloodTestSuccess = _bloodTestService.SetBloodTestResults((short) BloodTestRequestId, BloodTestResult, BloodTestDateTime);

            var prescription = _prescriptionService.GetPrescriptions(BloodTestRequests.Where(item => item.Id == BloodTestRequestId).First().PrescriptionId).ElementAt(0);

            var statusSuccess = _prescriptionService.SetPrescriptionStatus(prescription.Id, PrescriptionStatus.BloodworkReceived);

            await InitPageAsync();

            if (bloodTestSuccess == 1 && statusSuccess == 1)
            {
                TempData["EnterTestSuccess"] = $"Blood test results for blood test request {BloodTestRequestId} were {BloodTestResult} and received on {BloodTestDateTime}.";
            }
            else if (bloodTestSuccess != 1)
            {
                TempData["EnterTestFailure"] = $"Blood Test service returned error value.";
            }
            else
            {
                TempData["EnterTestFailure"] = $"Prescription service returned error value.";
            }
        }

        public async Task OnPostSearchAsync()
        {
            var patientIds = _userManager.Users.Where(item => item.FirstName.Contains(SearchTerm) || item.LastName.Contains(SearchTerm)).Select(item => item.Id);

            Prescriptions = _prescriptionService.GetPrescriptions().Where(item => patientIds.Contains(item.PatientId)).OrderBy(item => item.Id).ToList();

            var prescriptionIds = Prescriptions.Select(item => item.Id);

            BloodTests = _bloodTestService.GetBloodTests().ToList();
            BloodTestRequests = _bloodTestService.GetBloodTestRequests().Where(item => item.BloodTestStatus == BloodTestRequestStatus.Scheduled && prescriptionIds.Contains(item.PrescriptionId)).OrderBy(item => item.BloodTestStatus).ToList();

            await LoadPrescriptionsAndPatients();
        }

        private async Task InitPageAsync()
        {
            BloodTestRequests = _bloodTestService.GetBloodTestRequests().Where(item => item.BloodTestStatus == BloodTestRequestStatus.Scheduled).ToList();

            var bloodTestIds = BloodTestRequests.Select(item => item.BloodTestId);

            for (int i = 0; i < bloodTestIds.Count(); i++)
            {
                BloodTests.Add(_bloodTestService.GetBloodTests().Where(item => item.Id == bloodTestIds.ElementAt(i)).ElementAt(0));
            }

            await LoadPrescriptionsAndPatients();
        }

        private async Task LoadPrescriptionsAndPatients()
        {
            foreach (var item in BloodTestRequests)
            {
                Prescriptions.Add(_prescriptionService.GetPrescriptions(item.PrescriptionId).ElementAt(0));
            }

            foreach (var item in Prescriptions)
            {
                Patients.Add(await _userManager.FindByIdAsync(item.PatientId));
            }
        }
    }
}

AADWebApp/Areas/GeneralPractitioner/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AADWebApp.Areas.GeneralPractitioner.Pages
{
    [Authorize(Roles = "General Practitioner, Admin")]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

AADWebApp/Areas/GeneralPractitioner/Pages/RequestPrescription.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AADWebApp.Areas.Identity.Data;
using AADWebApp.Interfaces;
using AADWebApp.Models;
using AADWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AADWebApp.Areas.GeneralPractitioner.Pages
{
    [Authorize(Roles = "General Practitioner, Admin")]
    public class RequestPrescriptionModel : PageModel
    {
        private readonly IMedicationService _medicationService;
        private readonly IPatientService _patientService;
        private readonly IPrescriptionService _prescriptionService;
        private readonly UserManager<ApplicationUser> _userManager;

        public IEnumerable<Medication> Medications;
        public List<ApplicationUser> Patients = new List<ApplicationUser>();

        public SelectList IssueFrequencies = new SelectList(
            Enum.GetValues(typeof(PrescriptionService.IssueFrequency))
        );

        [BindProperty]
        public short MedicationId { get; set; }

        [BindProperty]
        public string Id { get; set; }

        [BindProperty]
        public int Dosage { get; set; }

        [BindProperty]
        public DateTime DateStart { get; set; }

        [BindProperty]
        public DateTime DateEnd { get; set; }

        [BindProperty]
        public PrescriptionService.IssueFrequency IssueFrequency { get; set; }

        [BindProperty]
        public string SearchTerm { get; set; }

        public RequestPrescriptionModel(IMedicationService medicationService, IPatientService patientService, IPrescriptionService prescriptionService, UserManager<ApplicationUser> userManager)
        {
            _medicationService = medicationService;
            _patientService = patientService;
            _prescriptionService = prescriptionService;
            _userManager = userManager;
        }

        public async Task OnGetAsync()
        {
            await InitPage();
        }

        public async Task OnPostPrescribeAsync()
        {
            await InitPage();

            var isSuccess = _prescriptionService.CreatePrescription(MedicationId, Id, Dosage, DateStart, DateEnd, IssueFrequency);

            if (isSuccess == 1)
            {
                TempData["PrescriptionRequestSuccess"] = $"Prescription successfully issued, with {IssueFrequency} dosages of {Dosage}mg between {DateStart.ToShortDateString()} and {DateEnd.ToShortDateString()}.";
            }
            else
            {
                TempData["PrescriptionRequestFailure"] = $"Failed to prescribe medication.";
            }
        }

        public async Task OnPostSearchAsync()
        {
            Medications = _medicationService.GetMedications().Where(item => item.MedicationName.Contains(SearchTerm)).OrderBy(item => item.MedicationName);
            
            foreach (var patient in _patientService.GetPatients())
            {
                Patients.Add(await _userManager.FindByIdAsync(patient.Id));
            }
        }

        private async Task InitPage()
        {
            Medications = _medicationService.GetMedications().OrderBy(item => item.MedicationName);

            foreach (var patient in _patientService.GetPatients())
            {
                Patients.Add(await _userManager.FindByIdAsync(patient.Id));
            }
        }
    }
}

AADWebApp/Areas/GeneralPractitioner/Pages/ScheduleBloodwork.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AADWebApp.Areas.Identity.Data;
using AADWebApp.Interfaces;
using AADWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AADWebApp.Areas.GeneralPractitioner.Pages
{
    [Authorize(Roles = "General Practitioner, Admin")]
    public class ScheduleBloodworkModel : PageModel
    {
        private readonly IBloodTestService _bloodTestService;
        private readonly IPrescriptionService _prescriptionService;
        private readonly IMedicationService _medicationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public List<BloodTestRequest> BloodTestRequests { get; private set; }
        public List<Prescription> Prescriptions { get; private set; }
        public List<Medication> Medications { get; private set; }
        public List<ApplicationUser> Patients { get; private set; }

        [BindProperty]
        public int PrescriptionId { get; set; }

        [BindProperty]
        public int BloodTestRequestId { get; set; }

        [BindProperty]
        public DateTime AppointmentDateTime { get; set; }

        [BindProperty]
        public string SearchTerm { get; set; }

        public ScheduleBloodworkModel(IBloodTestService bloodTestService, IPrescriptionService prescriptionService, IMedicationService medicationService, UserManager<ApplicationUser> userManager)
        {
            _bloodTestService = bloodTestService;
            _prescriptionService = prescriptionService;
            _medicationService = medicationService;
            _userManager = userManager;
        }

        public async Task OnGetAsync()
        {
            await InitPageAsync();
        }

        public async Task OnPostAsync()
        {
            await InitPageAsync();

            var isSuccess = await _bloodTestService.SetBloodTestDateTimeAsync(Prescriptions.First(item => item.Id == PrescriptionId), (short) BloodTestRequestId, AppointmentDateTime);

            await InitPageAsync();

            if (isSuccess == 1)
            {
                TempData["ScheduleBloodworkSuccess"] = $"A blood test request {BloodTestRequestId} (prescription ID {PrescriptionId}) has been booked for {AppointmentDateTime}.";
            }
            else
            {
                TempData["ScheduleBloodworkFailure"] = $"Blood Test service returned error value.";
            }
        }

        public async Task OnPostSearchAsync()
        {
            BloodTestRequests = new List<BloodTestRequest>();
            Prescriptions = new List<Prescription>();
            Medications = new List<Medication>();
            Patients = new List<ApplicationUser>();

            var patientIds = _userManager.Users.Where(item => item.FirstName.Contains(SearchTerm) || item.LastName.Contains(SearchTerm)).Select(item => item.Id);

            Prescriptions = _prescriptionService.GetPrescriptions().Where(item => patientIds.Contains(item.PatientId)).OrderBy(item => item.Id).ToList();

            var prescriptionIds = Prescriptions.Select(item => item.Id);

            BloodTestRequests = _bloodTestService.GetBloodTestRequests().Where(item => prescriptionIds.Contains(item.PrescriptionId)).OrderBy(item => item.BloodTestStatus).ToList();

            await LoadBloodTestRequestsAndPrescriptionsAsync();
        }

        private async Task InitPageAsync()
        {
            BloodTestRequests = new List<BloodTestRequest>();
            Prescriptions = new List<Prescription>();
            Medications = new List<Medication>();
            Patients = new List<ApplicationUser>();

            BloodTestRequests = _bloodTestService.GetBloodTestRequests().OrderBy(item => item.BloodTestStatus).ToList();

            await LoadBloodTestRequestsAndPrescriptionsAsync();
        }

        private async Task LoadBloodTestRequestsAndPrescriptionsAsync()
        {
            foreach (var item in BloodTestRequests)
            {
                Prescriptions.Add(_prescriptionService.GetPrescriptions(item.PrescriptionId).ElementAt(0));
            }

            foreach (var item in Prescriptions)
            {
                Medications.Add(_medicationService.GetMedications(item.MedicationId).ElementAt(0));
                Patients.Add(await _userManager.FindByIdAsync(item.PatientId));
            }
        }
    }
}

AADWebApp/Areas/GeneralPractitioner/Pages/CancelPrescription.cshtml
@page
@using AADWebApp.Services
@model AADWebApp.Areas.GeneralPractitioner.Pages.CancelPrescriptionModel
@{
    ViewData["Title"] = "Cancel Prescription";
    Layout = "~/Areas/GeneralPractitioner/Pages/_GeneralPractitionerLayout.cshtml";
}

<h1 class="mb-5">Cancel Prescription</h1>

<h3 class="mb-5">Search</h3>

<div id=" Search" class="form-group form-inline mb-5">
    <form method="post" class="form-inline">
        <div class="form-group">
            <label for="medication-name" class="mr-5">Patient Name</label>
            <input type="text" class="form-control mr-5" id="medication-name" name="SearchTerm" placeholder="Patient Name">
        </div>
        <button type="submit" asp-page-handler="Search" class="btn btn-primary">Search</button>
    </form>
    <form method="get">
        <button type="submit" asp-page-handler="OnGet" class="btn btn-primary ml-5">Clear</button>
    </form>
</div>

@if (TempData["PrescriptionCancelSuccess"] != null)
{
    <p class="mb-2 p-2 bg-success text-white rounded">@TempData["PrescriptionCancelSuccess"]</p>
}
else if (TempData["PrescriptionCancelFailure"] != null)
{
    <p class="mb-2 p-2 bg-danger text-white rounded">@TempData["PrescriptionCancelFailure"]</p>
}

<table class="table table-sm table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">Prescription ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Medication Name</th>
            <th scope="col">Issue Frequency</th>
            <th scope="col">Status</th>
            <th scope="col">Prescription Start</th>
            <th scope="col">Prescription End</th>
            <th scope="col">Cancel</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Prescriptions.Count(); i++)
        {
            var isCancelled = Model.Prescriptions[i].PrescriptionStatus == PrescriptionService.PrescriptionStatus.Terminated;

            <form method="POST">
                <input type="hidden" value="@Model.Prescriptions[i].Id" name="Id" />
                <tr>
                    <td>@Model.Prescriptions[i].Id</td>
                    <td>@Model.Patients[i].FirstName</td>
                    <td>@Model.Patients[i].LastName</td>
                    <td>@Model.Medications[i].MedicationName</td>
                    <td>@Model.Prescriptions[i].IssueFrequency</td>
                    <td>@Model.Prescriptions[i].PrescriptionStatus</td>
                    <td>@Model.Prescriptions[i].DateStart.ToShortDateString()</td>
                    <td>@Model.Prescriptions[i].DateEnd.ToShortDateString()</td>
                    <td>
                        <input type="submit" class="btn btn-danger float-right" value="Cancel" @(isCancelled ? "disabled" : "") />
                    </td>
                </tr>
            </form>
        }
    </tbody>
</table>

AADWebApp/Areas/GeneralPractitioner/Pages/EnterTestResults.cshtml
@page
@model AADWebApp.Areas.GeneralPractitioner.Pages.EnterTestResultsModel
@{
    ViewData["Title"] = "Enter Test Results";
    Layout = "~/Areas/GeneralPractitioner/Pages/_GeneralPractitionerLayout.cshtml";
}

<h1 class="mb-5">Enter Test Results</h1>

<h3 class="mb-5">Search</h3>

<div id=" Search" class="form-group form-inline mb-5">
    <form method="post" class="form-inline">
        <div class="form-group">
            <label for="medication-name" class="mr-5">Patient Name</label>
            <input type="text" class="form-control mr-5" id="medication-name" name="SearchTerm" placeholder="Patient Name">
        </div>
        <button type="submit" asp-page-handler="Search" class="btn btn-primary">Search</button>
    </form>
    <form method="get">
        <button type="submit" asp-page-handler="OnGet" class="btn btn-primary ml-5">Clear</button>
    </form>
</div>

@if (TempData["EnterTestSuccess"] != null)
{
    <p class="mb-2 p-2 bg-success text-white rounded">@TempData["EnterTestSuccess"]</p>
}
else if (TempData["EnterTestFailure"] != null)
{
    <p class="mb-2 p-2 bg-danger text-white rounded">@TempData["EnterTestFailure"]</p>
}

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Blood Test Request ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Blood Test Type</th>
            <th scope="col">Blood Test Date/Time</th>
            <th scope="col" colspan="2">Results</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.BloodTestRequests.Count; i++)
        {
            <form method="post">
                <input type="hidden" value="@Model.BloodTestRequests[i].Id" name="BloodTestRequestId" />

                <tr>
                    <td>@Model.BloodTestRequests[i].Id</td>
                    <td>@Model.Patients[i].FirstName</td>
                    <td>@Model.Patients[i].LastName</td>
                    <td>@Model.BloodTests[i].FullTitle</td>
                    <td>
                        <input required type="datetime-local" class="form-control" name="BloodTestDateTime">
                    </td>
                    <td>
                        <input required type="radio" name="BloodTestResult" value="true" class="form-check-input" id="Pass">
                        <label class="form-check-label" for="Pass">Pass</label>
                    </td>
                    <td>
                        <input required type="radio" name="BloodTestResult" value="false" class="form-check-input" id="Fail">
                        <label class="form-check-label" for="Pass">Fail</label>
                    </td>
                    <td>
                        <input type="submit" class="btn btn-success float-right" value="Submit" />
                    </td>
                </tr>
            </form>
        }
    </tbody>
</table>

AADWebApp/Areas/GeneralPractitioner/Pages/Index.cshtml
@page
@model AADWebApp.Areas.GeneralPractitioner.Pages.IndexModel
@{
    ViewData["Title"] = "General Practitioner Home";
    Layout = "~/Areas/GeneralPractitioner/Pages/_GeneralPractitionerLayout.cshtml";
}

<h1 class="mb-5 mt-5">General Practitioner Home</h1>

<div class="card-deck mt-5 mb-5">
    <div class="card ml-5">
        <img class="card-img-top" src="~/lib/Images/MedicineBottle.png" style="height:300px">
        <div class="card-body">
            <a class="text-dark" asp-area="GeneralPractitioner" asp-page="/RequestPrescription">
                <h5 class="card-title"> <b>Request Prescription</b></h5>
            </a>
            <p class="card-text">Request a Prescription to be approved for a patient.</p>
        </div>
    </div>
    <div class="card ml-5">
        <img class="card-img-top" src="~/lib/Images/Doctor-Patient.png" style="height:300px">
        <div class="card-body">
            <a class="text-dark" asp-area="GeneralPractitioner" asp-page="/CancelPrescription">
                <h5 class="card-title"><b>Cancel Prescriptions</b></h5>
            </a>
            <p class="card-text">Cancel unwanted Prescriptions for patients.</p>
        </div>
    </div>


</div>

<div class="card-deck mt-5 mb-5">
    <div class="card ml-5">
        <img class="card-img-top" src="~/lib/Images/BloodTestingShirt.png">
        <div class="card-body">
            <a class="text-dark" asp-area="GeneralPractitioner" asp-page="/ScheduleBloodwork">
                <h5 class="card-title"> <b>Schedule Bloodwork</b></h5>
            </a>
            <p class="card-text">Schdeule a blood test requested by a pharmacist.</p>
        </div>
    </div>
    <div class="card ml-5">
        <img class="card-img-top" src="~/lib/Images/Results.png">
        <div class="card-body">
            <a class="text-dark" asp-area="GeneralPractitioner" asp-page="/EnterTestResults">
                <h5 class="card-title"><b>Enter Results</b></h5>
            </a>
            <p class="card-text">Enter Results of blood tests.</p>
        </div>
    </div>


</div>

AADWebApp/Areas/GeneralPractitioner/Pages/RequestPrescription.cshtml
@page
@using AADWebApp.Models
@model AADWebApp.Areas.GeneralPractitioner.Pages.RequestPrescriptionModel
@{
    ViewData["Title"] = "Request Prescription";
    Layout = "~/Areas/GeneralPractitioner/Pages/_GeneralPractitionerLayout.cshtml";
}

<h1 class="mb-5">Request Prescription</h1>

<h3 class="mb-5">Search</h3>

<div id=" Search" class="form-group form-inline mb-5">
    <form method="post" class="form-inline">
        <div class="form-group">
            <label for="medication-name" class="mr-5">Medication Name</label>
            <input type="text" class="form-control mr-5" id="medication-name" name="SearchTerm" placeholder="Medication Name">
        </div>
        <button type="submit" asp-page-handler="Search" class="btn btn-primary">Search</button>
    </form>
</div>

@if (TempData["PrescriptionRequestSuccess"] != null)
{
    <p class="mb-2 p-2 bg-success text-white rounded">@TempData["PrescriptionRequestSuccess"]</p>
}
else if (TempData["PrescriptionRequestFailure"] != null)
{
    <p class="mb-2 p-2 bg-danger text-white rounded">@TempData["PrescriptionRequestFailure"]</p>
}

<table class="table table-sm table-striped table-hover">
    <thead>
    <tr>
        <th scope="col">Medication Name</th>
        <th scope="col">Restriction Level</th>
        <th scope="col">Prescription Start</th>
        <th scope="col">Prescription End</th>
        <th scope="col">Dosage</th>
        <th scope="col">Issue Frequency</th>
        <th scope="col">Select</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var medication in Model.Medications)
    {
        <tr data-medication-id="@medication.Id">
            <td class="js-medication-name">@medication.MedicationName</td>
            <td class="js-medication-restriction-level">
                @if (medication.BloodWorkRestrictionLevel == null)
                {
                    @Html.Raw("<i>None</i>")
                }
                else
                {
                    @medication.BloodWorkRestrictionLevel.ToString()
                }
            </td>
            <td>
                <input type="date" class="form-control js-start-date" required />
            </td>
            <td>
                <input type="date" class="form-control js-end-date" required />
            </td>
            <td>
                <input type="number" class="form-control js-dosage" placeholder="Dosage (mg)" min="0" step="any" required />
            </td>
            <td>
                <select class="form-control js-issue-frequency" asp-items="@Model.IssueFrequencies">
                    <option value="">---</option>
                </select>
            </td>
            <td>
                <button data-toggle="modal" data-target="#request-prescription-patient-modal" class="btn btn-success float-right">Prescribe</button>
            </td>
        </tr>
    }
    </tbody>
</table>

<!--Modal-->
<div class="modal fade" tabindex="-1" id="request-prescription-patient-modal">
    <form method="POST">
        <div class="modal-dialog" role="form">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalTitle"> Choose Patient</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">First Name</th>
                                <th scope="col">Last Name</th>
                                <th scope="col">Select</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var patient in Model.Patients)
                            {
                                <tr>
                                    <td>@patient.FirstName</td>
                                    <td>@patient.LastName</td>
                                    <td>
                                        <div id="CheckBox" class="form-check-input mt-0">
                                            <input type="radio" name="Id" value="@(patient.Id)" class="form-check-input" id="SelectPatient" required />
                                            <label for="SelectPatient">Choose</label>
                                        </div>
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-danger float-left" data-dismiss="modal" value="Cancel" />
                    <input type="submit" class="btn btn-primary float-right" value="Confirm" asp-page-handler="Prescribe"  />
                </div>
            </div>
        </div>
    </form>
</div>